### ISSUE TITLE
Inconsistent number of Bytecodes

### ISSUE THREAD

**Issue by PasinduTennage** [saeg/asm-defuse#19]
I am using asm-defuse to implement a simple program that counts the number of Bytecodes in a given java class file.

I use the `analyzer.getBasicBlocks();` to get the number of instructions in a block. Following is my working example.

`Contract.java` Example java file from which I generate the `.class` file

```
public class Contract {
    private double Cvar1;
    private float Cvar2;
    private char Cvar3;
    private String Cvar4;
    private int Cvar5;
    private long Cvar6;

    public int factorial(int N) {
        int product = 1;
        int j = 1;
        while (j <= N) {
            product *= j;
            j++;
        }

        return product;
    }
}
```

`Counter` is a helper class that keeps the static variable count

```
public class Counter {
    public static int count = 0;

    public static void print(){
        System.out.println("Number of byte codes: "+count+"");
    }
}
```

This is how I use asm-defuse to get the number of Bytecodes in each block

```
import br.usp.each.saeg.asm.defuse.FlowAnalyzer;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.*;
import org.objectweb.asm.tree.analysis.AnalyzerException;
import org.objectweb.asm.tree.analysis.BasicInterpreter;
import org.objectweb.asm.tree.analysis.BasicValue;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;


public class ByteCodeCounterBlock {

    public static void main(String[] args) throws IOException, AnalyzerException {

        FileInputStream is_c = new FileInputStream("target/classes/Counter.class");
        ClassReader cr_c = new ClassReader(is_c);
        final ClassNode classNode_c = new ClassNode();
        cr_c.accept(classNode_c, 0);


        FileInputStream is = new FileInputStream("target/classes/Contract.class");

        ClassReader cr = new ClassReader(is);
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);

        final ClassNode classNode = new ClassNode();
        cr.accept(classNode, 0);

        for (final MethodNode mn : classNode.methods) {

            FlowAnalyzer<BasicValue> analyzer = new FlowAnalyzer<BasicValue>(new BasicInterpreter());
            analyzer.analyze("package/ClassName", mn);

            int[][] basicBlocks = analyzer.getBasicBlocks();

            for (int i = 0; i < basicBlocks.length; i++) {
                System.out.println("Basic block " + i + " contains " + (basicBlocks[i].length) + " instructions");
            }

            int numIns = mn.instructions.size();
            InsnList instructions = new InsnList();
            for (int i = 0; i < numIns; i++) {
                instructions.add(mn.instructions.get(i));
            }
            ;

            for (int i = 0; i < numIns; i++) {
                for (int[] basicBlock : basicBlocks) {
                    if (basicBlock[0] == i) {
                        AbstractInsnNode node = instructions.get(i);
                        InsnList numCounting = new InsnList();
                        numCounting.add(new FieldInsnNode(Opcodes.GETSTATIC, classNode_c.name, "count", "I"));
                        numCounting.add(new LdcInsnNode(basicBlock.length));
                        numCounting.add(new InsnNode(Opcodes.IADD));
                        numCounting.add(new FieldInsnNode(Opcodes.PUTSTATIC, classNode_c.name, "count", "I"));
                        mn.instructions.insert(node, numCounting);
                        break;
                    }
                }
            }
        }


        FileOutputStream fos = new FileOutputStream("target/classes/Contract.class");
        classNode.accept(cw);
        fos.write(cw.toByteArray());
        fos.close();
    }


}

```

This code compiles correctly, but the output is not correct. The following is the generated `.class`

```
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

public class Contract {
    private double Cvar1;
    private float Cvar2;
    private char Cvar3;
    private String Cvar4;
    private int Cvar5;
    private long Cvar6;

    public Contract() {
        Counter.count += 5;
        super();
    }

    public int factorial(int N) {
        Counter.count += 8;
        int product = 1;
        int j = 1;

        while(true) {
            Counter.count += 6;
            if (j > N) {
                Counter.count += 5;
                return product;
            }

            Counter.count += 10;
            product *= j;
            ++j;
        }
    }
}

```

To test the correctness of the output, I count number of Bytecodes using the  standard asm library as follows.

```
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.*;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ListIterator;

public class ByteCodeCounterSeq {

    public static void main(String[] args) throws IOException {

        FileInputStream is_c = new FileInputStream("target/classes/Counter.class");
        ClassReader cr_c = new ClassReader(is_c);
        final ClassNode classNode_c = new ClassNode();
        cr_c.accept(classNode_c, 0);


        FileInputStream is = new FileInputStream("target/classes/Contract.class");

        ClassReader cr = new ClassReader(is);
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);

        final ClassNode classNode = new ClassNode();
        cr.accept(classNode, 0);
//        classNode.fields.add(new FieldNode(Opcodes.ACC_STATIC +Opcodes.ACC_PUBLIC, "count", "I", null, 0));


        for (final MethodNode mn : classNode.methods) {

            ListIterator<AbstractInsnNode> itr = mn.instructions.iterator();

            // core insert
            while (itr.hasNext()) {

                AbstractInsnNode node = itr.next();

                InsnList numCounting = new InsnList();

                // insert count++
                numCounting.add(new FieldInsnNode(Opcodes.GETSTATIC, classNode_c.name, "count", "I"));
                numCounting.add(new InsnNode(Opcodes.ICONST_1));
                numCounting.add(new InsnNode(Opcodes.IADD));
                numCounting.add(new FieldInsnNode(Opcodes.PUTSTATIC, classNode_c.name, "count", "I"));

                // insert print() for debug
//                numCounting.add(new MethodInsnNode(Opcodes.INVOKESTATIC, classNode_c.name, "print", "()V", false));

                mn.instructions.insert(node, numCounting);
            }
        }


        FileOutputStream fos = new FileOutputStream("target/classes/Contract.class");
        classNode.accept(cw);
        fos.write(cw.toByteArray());
        fos.close();
    }
}
```

The following is the output from the standard asm.

```
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

public class Contract {
    private double Cvar1;
    private float Cvar2;
    private char Cvar3;
    private String Cvar4;
    private int Cvar5;
    private long Cvar6;

    public Contract() {
        ++Counter.count;
        ++Counter.count;
        ++Counter.count;
        super();
        ++Counter.count;
    }

    public int factorial(int N) {
        ++Counter.count;
        ++Counter.count;
        ++Counter.count;
        int product = 1;
        ++Counter.count;
        ++Counter.count;
        ++Counter.count;
        ++Counter.count;
        int j = 1;
        ++Counter.count;

        while(true) {
            ++Counter.count;
            ++Counter.count;
            ++Counter.count;
            ++Counter.count;
            ++Counter.count;
            if (j > N) {
                ++Counter.count;
                ++Counter.count;
                ++Counter.count;
                ++Counter.count;
                return product;
            }

            ++Counter.count;
            ++Counter.count;
            ++Counter.count;
            ++Counter.count;
            ++Counter.count;
            int var10000 = product * j;
            ++Counter.count;
            product = var10000;
            ++Counter.count;
            ++Counter.count;
            ++Counter.count;
            ++j;
            ++Counter.count;
        }
    }
}
```

As you can see, the asm-defuse based counting is not correct. I compared the output `.class` files, and I found the following as some possible reasons.

1. ASM does not count the `return` statements, where as the ASM-Defuse does
2. ASM-Defuse does not divide the code into blocks correctly in the presence of `if`, `for` and `while`

Any idea on how to fix this?

Thanks

**Comment by andrioli** [comment]
Hi @PasinduTennage,

I have two concerns:

* On the standard ASM version you are updating the counter after an instructions, and it may create unreachable code. Indeed, this is happening to `return` instructions. This may explain why for the constructor you count five instructions using ASM-DefUse and count four instructions using plain ASM. You are not counting the `return` instruction. This may also affect loops. Maybe you can use the `insertBefore` method and also use `CheckMethodAdapter` class from `asm-util` to check if your instrumentation is correct. 

* My second concern is about the use of the basic block length as the number of instructions.  The instructions list contains some nodes that are used only to "flag" an instruction (e.g., `LabelNode`, `LineNumberNode`, `FrameNode`), so maybe you want to skip these "instructions".

**Comment by andrioli** [comment]
Hey @PasinduTennage  just a note when using `insertBefore` method for some `LabelNode`, you may inserting the instrumentation before the target of a jump, and the counting could be incorrect.

I'll close this issue and flag as a question, if you found a bug related to it, we can re-open the issue.

**Comment by PasinduTennage** [comment]
Hi @andrioli 

Thank you for the answer. I have some questions about your explanation.

Using `insertBefore` seems to be a possible option to mitigate unreachable codes, however, as you pointed out it may generate incorrect counting. To the best of your knowledge, what should be the ideal way to insert the counter?

I used the basic block length as the number of instructions, and it of course has some instructions that are book keeping. However, the non ASM-Defuse based approach also counts these book keeping instructions, so I am wondering whether it is an issue for the final counts.

Yes, this issue can be closed because the underlying reason does not have to do anything with the correctness of ASM-Defuse

Thank you

**Comment by PasinduTennage** [comment]
Hi @andrioli 

In particular, how can I remove the "book keeping instructions" from the block array? Is there any other way in ASM-DEFUSE where I can directly get the useful number of instructions in a block?

Thanks

**Comment by andrioli** [comment]
> Using `insertBefore` seems to be a possible option to mitigate unreachable codes, however, as you pointed out it may generate incorrect counting. To the best of your knowledge, what should be the ideal way to insert the counter?

What I normally do is always use `insertBefore` but I always insert before the first valid instruction of each block (in other words, after any target label). [Here](https://github.com/saeg/ba-dua/blob/ba-dua-0.6.0/ba-dua-core/src/main/java/br/usp/each/saeg/badua/core/internal/instr/CoverageMethodTransformer.java#L120-L140) is an example of how you can find the first valid instruction of each block.

> I used the basic block length as the number of instructions, and it of course has some instructions that are book keeping. However, the non ASM-Defuse based approach also counts these book keeping instructions, so I am wondering whether it is an issue for the final counts.

In both approaches you will be counting more instructions that the ones executed by the JVM; That's why I suggest you to skip these pseudo-instructions like `LabelNode`, `LineNumberNode` and `FrameNode`.

> In particular, how can I remove the "book keeping instructions" from the block array? Is there any other way in ASM-DEFUSE where I can directly get the useful number of instructions in a block?

My suggestion is to create a utility function pretty much like the example that find the first valid instruction, but that count the instructions!
